import { TokenizerEvent, ErrorStrategy } from './types';
export declare class Tokenizer {
    private legalTags;
    private tagCharPattern;
    private maxBufferSize;
    private maxNestingDepth;
    private state;
    private buffer;
    private flushedIndex;
    private eventQueue;
    private tagName;
    private attrName;
    private attrValue;
    private attributes;
    private depth;
    private ended;
    constructor(legalTags?: string[], tagCharPattern?: RegExp, maxBufferSize?: number, errorStrategy?: ErrorStrategy, maxNestingDepth?: number);
    write(chunk: string): void;
    end(): void;
    reset(): void;
    pull(): TokenizerEvent | null;
    /** Flush text from last flush point up to the given buffer position */
    flushUpTo(bufferPos: number): string;
    flushPendingText(): string;
    isInTagSuspect(): boolean;
    currentDepth(): number;
    setMaxNestingDepth(depth: number): void;
    private processChar;
    private suspectStartPos;
    private handleText;
    private handleTagSuspect;
    private handleTagName;
    private handleAfterName;
    private handleAttrName;
    private handleBeforeAttrEq;
    private handleAttrValueStart;
    private handleAttrValueDQ;
    private handleAttrValueSQ;
    private handleBeforeClose;
    private handleCloseTagName;
    private isNameChar;
    private validateTagName;
    private matchesPrefix;
    private emitElementOpen;
    private emitElementClose;
    private emitSelfClose;
    private resetTagState;
    private compactBuffer;
}
